server:
  port: 8081

spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_almacen?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Developer123.

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
    client:
      service-url:
        defaultZone: http://admin:admin123@localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 30
      eureka-server-connect-timeout-seconds: 10
