server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_almacen?useSSL=false&serverTimezone=UTC
    username: root
    password: Developer123.

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

